name: bootcamp411 deploy

on:
  push:
    branches: [ master ]
  
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Install Node
      uses: actions/setup-node@v2-beta
      with:
        node-versio:: 12
        
    - name: installing surge
      run: npm install --global surge
    - name: deploying using surge
      run: surge ./ bootcamp4112.surge.sh --token $ {{ secrets.Token }}
       
